added config check

diff --git a/actions.yml b/actions.yml
--- a/actions.yml
+++ b/actions.yml
@@ -5,24 +5,42 @@ inputs:
     description: 'Username'
     required: true
   reponame:
-    description: 'Name of the repo where the actyion is added.'
+    description: 'Reponame'
     required: true
   token:
     description: 'Your Github token'
     required: true
   buildscript:
-    description: 'Build script specified in packgae.json By default takes build as the script).'
+    description: 'Build script specified in package.json (By default takes build as the script).'
     required: false
     default: 'build'
   basebranchname:
-    description: 'Build script specified in packgae.json By default takes build as the script).'
+    description: 'Base branch through which the gh pages should be created'
     required: false
-    default: 'main'
+    default: 'master'
+  email:
+    description: 'Email for git config'
+    required: false
+    default: 'action@example.com'
+  name:
+    description: 'Name for Git Config'
+    required: false
+    default: 'action'
+  commitmessage:
+    description: 'Commit message for creation of gh pages'
+    required: false
+    default: 'Create gh-pages'
 runs:
   using: "composite"
   steps:
       - name: Build Vue
         run: |
+              CONFIGFILE=vue.config.js
+              if [ ! -f "$CONFIGFILE" ]; then
+                  echo "$CONFIGFILE does not exist."
+                  echo "::error ::vue config file missing"
+                  exit 1
+              fi
               npm ci
               npm run build
         shell: bash
@@ -30,8 +48,10 @@ runs:
         run: |
               cd dist
               ln -s index.html 404.html
+              git config --global user.email "${{ inputs.email }}"
+              git config --global user.name "${{ inputs.name }}"
               git init
               git add .
-              git commit -m '${{ inputs.gitmsg }}'
+              git commit -m '${{ inputs.commitmessage }}'
               git push -f https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git ${{ inputs.basebranchname }}:gh-pages
         shell: bash
